spring:
    jpa:
         hibernate:
             ddl-auto: update
             naming:
                  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
         jndi-name: jdbc/demo-hello   
server:
    port: 8181
    servlet:
         context-path: /api 
application:
    title: Demo Hello
    version: 1.0.1