spring:
    config:
      import: classpath:.env.properties
    jpa:
         show-sql: true
         hibernate:
             ddl-auto: update
             naming:
                  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
         jndi-name: jdbc/demo-hello
server:
    port: 8181
    servlet:
         context-path: /api 
application:
    title: Demo Hello
    version: 1.0.0

security:
    jwt:
      expiration-in-minutes: ${EXPIRATION_IN_MINUTES}
      secret-key: ${SECRET_KEY}

spring-doc:
    swagger-ui:
         enabled: true
         path: /swagger-ui.html
    api-docs:
         enabled: true
    pathsToMatch: /person/**, /