name: Deploy Spring Boot App

on:
  pull_request:
    types: [ closed ]
       
jobs:
   sonarqube_scan:
      runs-on: self-hosted
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Set up Java to tests
        run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV
            
      - name: SonarQube Scan In Production
        run: /opt/apache-maven-3.9.6/bin/mvn verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.host.url=${{ secrets.SONAR_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }}
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          SONAR_JAVA_PATH: ${{ env.JAVA_HOME }}/bin/java
          
   test:
      needs: sonarqube_scan
      runs-on: self-hosted
      if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master'
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java to tests
        run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV

      - name: Run Tests In Production
        run: |
          /opt/apache-maven-3.9.6/bin/mvn clean test
        env:
          DB_DATABASE: $DB_DATABASE
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
          EXPIRATION_IN_MINUTES: ${{ secrets.EXPIRATION_IN_MINUTES }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
          
   build:
      needs: test
      runs-on: self-hosted
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Java to build
          run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV
      
        - name: Build
          run: |
            /opt/apache-maven-3.9.6/bin/mvn clean install package -DskipTests
          env:        
            EXPIRATION_IN_MINUTES:  ${{ secrets.EXPIRATION_IN_MINUTES }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            JAVA_HOME: ${{ env.JAVA_HOME }}
          
   deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Stop Tomcat
          run: |
            sudo systemctl stop tomcat-10.service
            while sudo systemctl is-active --quiet tomcat-10.service; do
              echo "Waiting stop tomcat"
              sleep 5
            done
            echo "Tomcat is stopped"
          
        - name: Replace WAR file
          run: |
            rm -rf /opt/tomcat-10/webapps/demo-hello
            rm -rf /opt/tomcat-10/webapps/demo-hello.war
            cp -rf /opt/actions-runner/_work/spring-hello/spring-hello/target/demo-hello-0.0.1-SNAPSHOT.war /opt/tomcat-10/webapps/demo-hello.war
    
        - name: Start Tomcat
          run: |
            systemctl start tomcat-10.service
            while ! curl -s http://localhost:8080 >/dev/null; do
              echo "Waiting for Tomcat to start..."
              sleep 5
            done
            echo "Tomcat is up and running"
  
        - name: Finish
          run: echo "Application deployed ​successfully"
