name: Deploy Spring Boot App

on:
  push:
    branches:
       ["master"]
       
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Deploy
        run:  sudo mvn clean install

      - name: Complete
        run: sudo java -jar /opt/actions-runner/_work/spring-hello/target/demo-hello-0.0.1-SNAPSHOT.jar &
