name: Deploy Spring Boot App

on:
  push:
    branches:
       ["master"]
       
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
    
      - name: Build and Deploy
        run: |
          /opt/apache-maven-3.8.4/bin/mvn clean install
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
      
      - name: Complete
        run: sudo java -jar /opt/actions-runner/_work/spring-hello/target/demo-hello-0.0.1-SNAPSHOT.jar &
