name: Deploy Spring Boot App

on:
  push:
    branches:
       ["master"]
       
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV
    
      - name: Build and Deploy
        run: |
          /opt/apache-maven-3.9.6/bin/mvn clean install package
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
      
      - name: Complete and Start Application
        run: |
          java -jar /opt/actions-runner/_work/spring-hello/spring-hello/target/demo-hello-0.0.1-SNAPSHOT.jar &
          PID=$!  # Obtener el ID del proceso
          echo "PID del proceso de la aplicación Spring Boot: $PID"
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
