name: Test Spring Boot App in dev branch

on:
  push:
    branches:
      ["dev"]

jobs:
  sonarqube_scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Java to tests
        run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV
    
      - name: SonarQube Scan
        run: /opt/apache-maven-3.8.4/bin/mvn sonar:sonar \
             -Dsonar.projectKey=demo-hello-key \
             -Dsonar.host.url="http://68.183.123.51:9088" \
             -Dsonar.login=sqp_c38e6b149ec9d3cdac5a6232d43c535cb85318a9
        env: 
          JAVA_HOME: ${{ env.JAVA_HOME }}
          SONAR_JAVA_PATH: ${{ env.JAVA_HOME }}/bin/java


  test:
    needs: sonarqube_scan
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java to tests
        run: echo "JAVA_HOME=/usr/lib/jvm/open-jdk-17" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          /opt/apache-maven-3.8.4/bin/mvn clean test
        env:
          DB_DATABASE: $DB_DATABASE
          DB_USER: $DB_USER
          DB_PASSWORD: $DB_PASSWORD
          EXPIRATION_IN_MINUTES: ${{ secrets.EXPIRATION_IN_MINUTES }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
